server {
    listen 0.0.0.0:8080;
    root www;
    index index.html;
    client_max_body_size 10485760;
    autoindex off;
    allow_methods GET;
    error_page 404 www/errors/404.html;

    location /files {
        root www/files;
        index index.html;
        autoindex on;
        allow_methods GET DELETE;
    }

    location /upload {
        root www/uploads;
        index index.html;
        autoindex on;
        allow_methods GET POST DELETE;
        upload_dir www/uploads;
    }

    location /health {
        root www/health;
        index index.html;
        autoindex off;
        allow_methods GET;
    }

    location /admin {
        root www/admin;
        index index.html;
        autoindex off;
        allow_methods GET;
    }

    location /cgi-bin {
        root www/cgi-bin;
        allow_methods GET POST;
        cgi_handler .py /usr/bin/python3;
        cgi_handler .php /usr/bin/php-cgi;
        cgi_timeout 3;
    }
}
