name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ircserv
        run: make -C prd

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build unit tests
        run: make -C tests
      - name: Run unit tests
        run: make -C tests run
